abaseurl = "http://blog.inaho.top"
title = "inaho"
theme = "hugo-coder"
languagecode = "zh-cn"
defaultcontentlanguage = "zh-cn"
enableEmoji = true

[pagination]
pagerSize = 6

[services]
[services.disqus]
# Enable Disqus comments
# shortname = "yourdiscussshortname"

[markup]
[markup.highlight]
noClasses = false

[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true

[params]
  author = "一个梦想家"
  info = "生之微欢，俄而感怀，奋勉有得，相携互舍，所谓幸福"
  description = "珍藏多年的文章"
  keywords = "blog,developer,personal"
  avatarurl = "images/avatar.png"
  gravatar = "1031567135@qq.com"

  faviconSVG = "/img/favicon.svg"
  favicon_32 = "/img/favicon-32x32.png"
  favicon_16 = "/img/favicon-16x16.png"

  since = 2019

  enableTwemoji = true

  colorScheme = "auto"
  hidecolorschemetoggle = false
  twikoo = true
  maxSeeAlsoItems = 5

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

# Social links
[[params.social]]
  name = "Github"
  icon = "fa-brands fa-github fa-2x"
  weight = 1
  url = "https://github.com/johndoe/"
[[params.social]]
  name = "Gitlab"
  icon = "fa-brands fa-gitlab fa-2x"
  weight = 2
  url = "https://gitlab.com/johndoe/"
[[params.social]]
  name = "Twitter"
  icon = "fa-brands fa-x-twitter fa-2x"
  weight = 3
  url = "https://twitter.com/johndoe/"
[[params.social]]
  name = "LinkedIn"
  icon = "fa-brands fa-linkedin fa-2x"
  weight = 4
  url = "https://www.linkedin.com/in/johndoe/"
[[params.social]]
  name = "Medium"
  icon = "fa-brands fa-medium fa-2x"
  weight = 5
  url = "https://medium.com/@johndoe"
[[params.social]]
  name = "RSS"
  icon = "fa-solid fa-rss fa-2x"
  weight = 6
  url = "https://myhugosite.com/index.xml"
  rel = "alternate"
  type = "application/rss+xml"

# Menu links
[[menu.main]]
  name = "文章"
  weight = 1
  url  = "posts/"
[[menu.main]]
  name = "标签"
  weight = 2
  url = "tags/"
[[menu.main]]
  name = "分类"
  weight = 3  
  url = "categories/"
[[menu.main]]
  name = "关于"
  weight = 4
  url = "about/"