baseURL = "https://lznauy.cn"
title = "lznauy的技术小屋"
theme = "hugo-coder"
languagecode = "zh-cn"
defaultcontentlanguage = "zh-cn"
enableEmoji = true
buildFuture = true

[pagination]
  pagerSize = 20

[markup]
[markup.highlight]
  noClasses = false
[markup.tableOfContents]
  startLevel = 1   # 从一级标题开始显示
  endLevel = 6     # 到六级标题结束
  ordered = false  # 使用无序列表

[markup.goldmark]
[markup.goldmark.renderer]
  unsafe = true
[markup.goldmark.extensions]
  [markup.goldmark.extensions.math]
    enable = true
  [markup.goldmark.extensions.cjk]
    enable = true
    eastAsianLineBreaks = true
    neutralCharacters = ""
  [markup.goldmark.extensions.passthrough]
    enable = true
    [markup.goldmark.extensions.passthrough.delimiters]
      block = [['$$', '$$'], ['\\[', '\\]']]
      inline = [['$', '$'], ['\\(', '\\)']]

[params]
  author = "lznauy"
  info = ["生之微欢，俄而感怀，奋勉有得，相携互舍，所谓幸福"]
  description = "珍藏多年的文章"
  keywords = "blog,developer,personal"
  avatarurl = ""
  gravatar = "1031567135@qq.com"
  series = true

  since = 2019
  colorScheme = "auto"
  hidecolorschemetoggle = false
  twikoo = true
  maxSeeAlsoItems = 5
  dateFormat = "2006-01-02 15:04:05"

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

# Social links
[[params.social]]
  name = "Github"
  icon = "fa-brands fa-github fa-2x"
  weight = 1
  url = "https://github.com/IInaho"
[[params.social]]
  name = "RSS"
  icon = "fa-solid fa-rss fa-2x"
  weight = 6
  url = "https://lznauy.cn/index.xml"
  rel = "alternate"
  type = "application/rss+xml"

# Menu links
[[menu.main]]
  name = "文章"
  weight = 1
  url  = "posts/"
[[menu.main]]
  name = "菜谱"
  weight = 2
  url = "recipes/"
[[menu.main]]
  name = "标签"
  weight = 3
  url = "tags/"
[[menu.main]]
  name = "分类"
  weight = 4  
  url = "categories/"
[[menu.main]]
  name = "关于"
  weight = 5
  url = "about/"
[[menu.main]]
  name = "友链"
  weight = 6
  url = "friends/"
[[menu.main]]
  name = "AI"
  weight = 7
  url = "aitools/"